{
	"version": 1739264278,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/play-sheet0.png",
		"images/drakevskendrick-sheet0.png",
		"images/singer-sheet0.png",
		"images/singer-sheet1.png",
		"images/kendrick2-sheet0.png",
		"images/kendrick2-sheet1.png",
		"images/drake2-sheet0.png",
		"images/drake2-sheet1.png",
		"images/wtfcoin-sheet0.png",
		"images/point_left-sheet0.png",
		"images/sprite4sheet-sheet0.png",
		"images/sprite11sheet-sheet0.png",
		"images/tiledbackground.png",
		"images/light-sheet0.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/puch 1.m4a",
		"media/puch 1.ogg",
		"media/puch 2.m4a",
		"media/puch 2.ogg",
		"media/puch 3.m4a",
		"media/puch 3.ogg",
		"media/puch 4.m4a",
		"media/puch 4.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}